name: Deploy to chromatic

on:
  push:
    branches:
      - "otus-storybook-react"

jobs:
  deploy-to-cromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔌
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Npm install 🛒
        run: npm ci

      - name: Deploy to chromatic 🚀
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
