name: Deploy to chromatic


on:
    push:
      branches:
      - "otus-storybook-react"

jobs:
    deploy-to-cromatic:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout 🔌
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Npm install 🛒
              run: npm install --legacy-peer-deps

            - name: Deploy to chromatic 🚀
              uses: chromaui/action@v1
              with:
                projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                token: ${{ secrets.GITHUB_TOKEN }}
    chromatic-comment:
      name: Add chromatic link comment
      runs-on: ubuntu-latest
      steps:
        - uses: mshick/add-pr-comment@v1
          env:
            token: ${{ secrets.GITHUB_TOKEN }}
          with:
            message: |
              You can check this code in chromatic with the link
              https://www.chromatic.com/builds?appId=${{ secrets.CHROMATIC_PROJECT_ID }}